- hosts: all
  become: yes
  remote_user: ubuntu
  tasks:
    - authorized_key:
        user: ubuntu
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '/home/davar/.ssh/id_rsa.pub') }}"
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
